# Generated by Django 4.2.30 on 2026-09-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
